### ISSUE TITLE
I met error when running 'catkin_make' command

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#1]
When I ran the 'catkin_make' command, It showed as flows:
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp: In member function ‘void Map::clear()’:
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:87:8: **error: ‘class grid_map::GridMap’ has no member named ‘setConstant’
   map_.setConstant("elevation", NAN);
        ^~~~~~~~~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:88:8: **error: ‘class grid_map::GridMap’ has no member named ‘setConstant’
   map_.setConstant("color", NAN);
        ^~~~~~~~~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:89:8: **error: ‘class grid_map::GridMap’ has no member named ‘setConstant’
   map_.setConstant("semantics", NAN);
        ^~~~~~~~~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:90:8: **error: ‘class grid_map::GridMap’ has no member named ‘setConstant’
   map_.setConstant("semantics_viz", NAN);
        ^~~~~~~~~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:91:8: **error: ‘class grid_map::GridMap’ has no member named ‘setConstant’
   map_.setConstant("view_angle", M_PI/2);
        ^~~~~~~~~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:92:8: **error: ‘class grid_map::GridMap’ has no member named ‘setConstant’
   map_.setConstant("num_points", 0);
        ^~~~~~~~~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp: In member function ‘void Map::resizeToBounds(const Vector2d&, const Vector2d&)’:
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:102:10: **error: ‘class grid_map::GridMap’ has no member named ‘grow’
     map_.grow(size, grid_map::GridMap::SW);
          ^~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:102:40: **error: ‘SW’ is not a member of ‘grid_map::GridMap’
     map_.grow(size, grid_map::GridMap::SW);
                                        ^~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:108:10: **error: ‘class grid_map::GridMap’ has no member named ‘grow’
     map_.grow(size, grid_map::GridMap::NE);
          ^~~~**
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/map.cpp:108:40: **error: ‘NE’ is not a member of ‘grid_map::GridMap’
     map_.grow(size, grid_map::GridMap::NE);
                                        ^~**
asoom_oss/CMakeFiles/asoom.dir/build.make:182: recipe for target 'asoom_oss/CMakeFiles/asoom.dir/src/map.cpp.o' failed
make[2]: *** [asoom_oss/CMakeFiles/asoom.dir/src/map.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp: In constructor ‘ASOOM::ASOOM(const ASOOM::Params&, const PoseGraph::Params&, const Rectifier::Params&, const DenseStereo::Params&, const Map::Params&)’:
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:17:5: error: ‘path’ was not declared in this scope
     path cache = path(getenv("HOME")) / path(".ros/asoom_cache");
     ^~~~
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:17:5: note: suggested alternatives:
In file included from /usr/include/c++/7/experimental/filesystem:37:0,
                 from /home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:3:
/usr/include/c++/7/experimental/bits/fs_path.h:79:9: note:   ‘std::experimental::filesystem::v1::__cxx11::path’
   class path
         ^~~~
/usr/include/c++/7/experimental/bits/fs_path.h:79:9: note:   ‘std::experimental::filesystem::v1::__cxx11::path’
/usr/include/c++/7/experimental/bits/fs_path.h:79:9: note:   ‘std::experimental::filesystem::v1::__cxx11::path’
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:18:16: error: ‘cache’ was not declared in this scope
     remove_all(cache);
                ^~~~~
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:18:16: note: suggested alternative: ‘ctanhq’
     remove_all(cache);
                ^~~~~
                ctanhq
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:18:5: error: ‘remove_all’ was not declared in this scope
     remove_all(cache);
     ^~~~~~~~~~
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:18:5: note: suggested alternatives:
In file included from /usr/include/c++/7/experimental/filesystem:39:0,
                 from /home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:3:
/usr/include/c++/7/experimental/bits/fs_ops.h:265:13: note:   ‘std::experimental::filesystem::v1::remove_all’
   uintmax_t remove_all(const path& __p, error_code& __ec) noexcept;
             ^~~~~~~~~~
/usr/include/c++/7/experimental/bits/fs_ops.h:265:13: note:   ‘std::experimental::filesystem::v1::remove_all’
In file included from /usr/include/eigen3/Eigen/Core:345:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /usr/local/include/gtsam/base/OptionalJacobian.h:22,
                 from /usr/local/include/gtsam/base/Matrix.h:27,
                 from /usr/local/include/gtsam/base/Manifold.h:22,
                 from /usr/local/include/gtsam/base/Lie.h:26,
                 from /usr/local/include/gtsam/base/VectorSpace.h:11,
                 from /usr/local/include/gtsam/geometry/Point2.h:20,
                 from /usr/local/include/gtsam/nonlinear/NonlinearFactorGraph.h:24,
                 from /home/ssz/catkin_ws/asoom/src/asoom_oss/include/asoom/pose_graph.h:3,
                 from /home/ssz/catkin_ws/asoom/src/asoom_oss/include/asoom/asoom.h:6,
                 from /home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:7:
/usr/include/eigen3/Eigen/src/Core/util/Meta.h:78:29: note:   ‘Eigen::internal::remove_all’
 template<typename T> struct remove_all { typedef T type; };
                             ^~~~~~~~~~
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:19:5: error: ‘create_directory’ was not declared in this scope
     create_directory(cache);
     ^~~~~~~~~~~~~~~~
/home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:19:5: note: suggested alternatives:
In file included from /usr/include/c++/7/experimental/filesystem:39:0,
                 from /home/ssz/catkin_ws/asoom/src/asoom_oss/src/asoom.cpp:3:
/usr/include/c++/7/experimental/bits/fs_ops.h:95:8: note:   ‘std::experimental::filesystem::v1::create_directory’
   bool create_directory(const path& __p, const path& attributes,
        ^~~~~~~~~~~~~~~~
/usr/include/c++/7/experimental/bits/fs_ops.h:95:8: note:   ‘std::experimental::filesystem::v1::create_directory’
asoom_oss/CMakeFiles/asoom.dir/build.make:62: recipe for target 'asoom_oss/CMakeFiles/asoom.dir/src/asoom.cpp.o' failed
make[2]: *** [asoom_oss/CMakeFiles/asoom.dir/src/asoom.cpp.o] Error 1
CMakeFiles/Makefile2:2864: recipe for target 'asoom_oss/CMakeFiles/asoom.dir/all' failed
make[1]: *** [asoom_oss/CMakeFiles/asoom.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

So why is this?   I has built the grid_map  dependencies

**Comment by iandouglas96** [comment]
Are you using the forked [grid_map](https://github.com/iandouglas96/grid_map) mentioned in the readme?

**Comment by SSZ1** [comment]
> Are you using the forked [grid_map](https://github.com/iandouglas96/grid_map) mentioned in the readme?

Yes，I used that forked version.    It seems that the GridMap.hpp file in the ASOOM project doesn't have setConstant() member indeed.
Maybe you put the wrong version of ASOOM...
![image](https://user-images.githubusercontent.com/36888758/184568531-6233df28-cc12-449e-a77e-1572296546c6.png)
![image](https://user-images.githubusercontent.com/36888758/184568604-2a1f1796-8af8-4ce3-be27-460964030369.png)
and the GridMap.cpp file in grid_map_core -> src folder does have setConstant() function. But the function belongs to Eigen LIB.
![image](https://user-images.githubusercontent.com/36888758/184568901-a13fc19f-4d0a-4a9c-a003-b9b81cc32329.png)

**Comment by iandouglas96** [comment]
The relevant `GridMap.hpp` is here: https://github.com/iandouglas96/grid_map/blob/master/grid_map_core/include/grid_map_core/GridMap.hpp and does include `setConstant`.  Are you 100% sure you're using that repo?

**Comment by SSZ1** [comment]
Oh~，Now I see. I did mistook the version of grid_map...   Sorry.....
But now I met a new problem:
When I ran "catkin_make",  it showed 'fatal error:filesystem: No such file or directory '
So I changed the asoom.cpp: `#include <filesystem>` to `#include <experimental/filesystem>`    and  changed `using namespace std::experimental::system`, but it showed as follows:
![image](https://user-images.githubusercontent.com/36888758/184643928-c430e5f0-9254-489e-9b2b-9baad0b0a1f1.png)
My PC 's Linux version is Ubuntu18.04 and My GCC is 7.5.0.  So what GCC version should the project use? How can you use `#include <filesystem>` in asoom.cpp file ?

**Comment by iandouglas96** [comment]
You need gcc 9 or newer, or equivalent compiler with c++17 support.

**Comment by SSZ1** [comment]
> You need gcc 9 or newer, or equivalent compiler with c++17 support.

OK. Thanks a lot. But GTSAM is built on Ubuntu18.04. And what ubuntu version did you use in the asoom project?

**Comment by iandouglas96** [comment]
You can compile GTSAM on whatever OS you want.  You can install GCC 9 on 18.04 (see https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04) as well.  I have built and run ASOOM on both 18.04 and 20.04.

**Comment by SSZ1** [comment]
> You can compile GTSAM on whatever OS you want. You can install GCC 9 on 18.04 (see https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04) as well. I have built and run ASOOM on both 18.04 and 20.04.

All right. Thanks a lot!

**Comment by SSZ1** [comment]
> You can compile GTSAM on whatever OS you want. You can install GCC 9 on 18.04 (see https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04) as well. I have built and run ASOOM on both 18.04 and 20.04.

Thanks again!  And I met another problem. I have installed the GCC 9 successfully and catkin_make the project successfully.
When I ran`roslaunch asoom asoom.launch`, it runs smoothly before I played the data bag.  But then I ran `rosbag play --clock asoom_demo.bag`, the "asoom.launch -running" terminal showed error as follows:
![image](https://user-images.githubusercontent.com/36888758/184837019-85ba64c5-8583-48f0-bee1-6f27cb9d5d5e.png)
and the bag played well but the rviz didn't have the map:
![image](https://user-images.githubusercontent.com/36888758/184837277-eb9a8e68-1f60-431b-9ea4-37af69282201.png)
So how should I fix this? Thanks a lot for your patience.

**Comment by iandouglas96** [comment]
Do the unit tests pass?  `catkin run_tests asoom`

**Comment by iandouglas96** [comment]
I just pushed an update which might address this issue.  Please pull it and recompile and let me know.

**Comment by SSZ1** [comment]
> Do the unit tests pass? `catkin run_tests asoom`

I ran `catkin run_tests asoom`，it seemed that the project had been catkin_makde already. So it can't be tested.
It showed as follows:
![image](https://user-images.githubusercontent.com/36888758/185017661-f2b6c8d4-4d2b-4d3f-a6a8-ec2c388fe8bc.png)

**Comment by SSZ1** [comment]
> I just pushed an update which might address this issue. Please pull it and recompile and let me know.

OK. Thanks very much. I'll pull it right now and reply to you ASAP.

**Comment by SSZ1** [comment]
> I just pushed an update which might address this issue. Please pull it and recompile and let me know.

It's OK now. It worked. Thanks for your kindly help and patience.
![image](https://user-images.githubusercontent.com/36888758/185019794-965496f6-0756-4afb-843a-051f59efddfe.png)

**Comment by iandouglas96** [comment]
Good to hear!  I would highly recommend using [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) instead of `catkin_make`, but you can run the unit tests with `catkin_make` using `catkin_make run_tests` or possibly `catkin_make run_tests_asoom`.

**Comment by SSZ1** [comment]
> Good to hear! I would highly recommend using [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) instead of `catkin_make`, but you can run the unit tests with `catkin_make` using `catkin_make run_tests` or possibly `catkin_make run_tests_asoom`.

All right! Thanks again! I'll try catkin_tools later.

**Comment by ydb1098323556** [comment]
> > Good to hear! I would highly recommend using [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) instead of `catkin_make`, but you can run the unit tests with `catkin_make` using `catkin_make run_tests` or possibly `catkin_make run_tests_asoom`.
> 
> All right! Thanks again! I'll try catkin_tools later.

Hey bro! I met such problem, it seems that you've passed it. Could you please help me?
I can run "catkin_make run_tests asoom" successfully. But when I run "roslaunch asoom asoom.launch", it would tell me that
![Screenshot from 2022-10-23 17-05-35](https://user-images.githubusercontent.com/106864156/197383788-94413c5f-5892-4205-a5e6-f0a27e50c7a2.png)

From your comment it seems that you have successfully run "roslaunch asoom asoom.launch". Have you met such problem? How did you solve it?

And if it is convenient, it is kind of you to add my QQ. QQ number is in my id.

**Comment by SSZ1** [comment]
> > > Good to hear! I would highly recommend using [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) instead of `catkin_make`, but you can run the unit tests with `catkin_make` using `catkin_make run_tests` or possibly `catkin_make run_tests_asoom`.
> > 
> > 
> > All right! Thanks again! I'll try catkin_tools later.
> 
> Hey bro! I met such problem, it seems that you've passed it. Could you please help me? I can run "catkin_make run_tests asoom" successfully. But when I run "roslaunch asoom asoom.launch", it would tell me that ![Screenshot from 2022-10-23 17-05-35](https://user-images.githubusercontent.com/106864156/197383788-94413c5f-5892-4205-a5e6-f0a27e50c7a2.png)
> 
> From your comment it seems that you have successfully run "roslaunch asoom asoom.launch". Have you met such problem? How did you solve it?
> 
> And if it is convenient, it is kind of you to add my QQ. QQ number is in my id.

Maybe it's because the version of GCC isn't suitable. I haven't met this problem before.

**Comment by SSZ1** [comment]
> > > Good to hear! I would highly recommend using [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) instead of `catkin_make`, but you can run the unit tests with `catkin_make` using `catkin_make run_tests` or possibly `catkin_make run_tests_asoom`.
> > 
> > 
> > All right! Thanks again! I'll try catkin_tools later.
> 
> Hey bro! I met such problem, it seems that you've passed it. Could you please help me? I can run "catkin_make run_tests asoom" successfully. But when I run "roslaunch asoom asoom.launch", it would tell me that ![Screenshot from 2022-10-23 17-05-35](https://user-images.githubusercontent.com/106864156/197383788-94413c5f-5892-4205-a5e6-f0a27e50c7a2.png)
> 
> From your comment it seems that you have successfully run "roslaunch asoom asoom.launch". Have you met such problem? How did you solve it?
> 
> And if it is convenient, it is kind of you to add my QQ. QQ number is in my id.

And I add your QQ. We can talk with it in detail.

**Comment by ashishedge** [comment]
I could not find the bag file here.
[Screenshot from 2023-05-25 12-04-26](https://github.com/iandouglas96/asoom_oss/assets/98515125/84a12491-ffaa-478e-aade-068e79855164)
Could you please let me know?

**Comment by SSZ1** [comment]
> 

Maybe you can just download bag [here](https://drive.google.com/file/d/1XzIDCkFKaATIreknPa39f1PhiEZI8kid/view).
