### ISSUE TITLE
Question about the Map

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#10]
Hi~bro. I has built the map successfully with my own device. Overall it looks good but there are some sharp parts and peaks in the details of the map. 

Here are the photos of the map :
![image](https://user-images.githubusercontent.com/36888758/206457382-b70e6f38-d896-4456-8bec-a5207f60c7c5.png)
![image](https://user-images.githubusercontent.com/36888758/206457549-f9f974cb-0014-4ed4-859f-fcefd70f52e0.png)
![image](https://user-images.githubusercontent.com/36888758/206457620-b4ab9c4f-75bd-4a83-bbe2-47cbf76a995e.png)
![image](https://user-images.githubusercontent.com/36888758/206457699-b3cb3ede-a34a-49a0-b3d4-6e02a5174492.png)
![image](https://user-images.githubusercontent.com/36888758/206457769-c55b724d-06c5-4004-a405-79a449ce82f3.png)
![image](https://user-images.githubusercontent.com/36888758/206457826-e780538a-548f-466a-b01a-377cc4dcc76e.png)

And there are also the sharp peaks at the underside of the map :
![image](https://user-images.githubusercontent.com/36888758/206458480-eb6f134d-842a-4639-98ab-87ff9585fc9d.png)

Here is the [video](https://drive.google.com/file/d/1X4xFfEkqAja2o4jBIJDduw8IzWz9YTfg/view?usp=share_link) of the built map. 

So do you have any idea how it goes？ What may be causing the sharp peaks in the map?  Thanks for your time. 

I play the bag from the UAV flying  in the air to landing.

**Comment by SSZ1** [comment]
It seemed because the matching of the frames.

**Comment by iandouglas96** [comment]
That doesn’t look too abnormal to me.  Sometimes the stereo or odometry isn’t perfect and there might be some anomalous depths, which results in those spikes.  It looks like the worst ones occur when the robot is at a lower altitude, so it might help to not start asoom until the robot has gotten to its mapping altitude.  I’m sure with some better filtering you could probably get rid of them as well.

**Comment by SSZ1** [comment]
> That doesn’t look too abnormal to me. Sometimes the stereo or odometry isn’t perfect and there might be some anomalous depths, which results in those spikes. It looks like the worst ones occur when the robot is at a lower altitude, so it might help to not start asoom until the robot has gotten to its mapping altitude. I’m sure with some better filtering you could probably get rid of them as well.

Thanks bro. which better filter do you think can get rid of them? Do you have any suggestions?

**Comment by iandouglas96** [comment]
You want to filter outliers somehow is all.  Maybe a median filter convolution or just thresholding points to a particular range.  But that's up to you and out of scope of asoom itself, so closing this issue.

**Comment by SSZ1** [comment]
> You want to filter outliers somehow is all. Maybe a median filter convolution or just thresholding points to a particular range. But that's up to you and out of scope of asoom itself, so closing this issue.

Thanks, bro.
