### ISSUE TITLE
Question about the Pose.

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#11]
Hi~bro. I replaced  OrbSALM3 with the other slam algorithm -GVINS, which is tightly coupled with GNSS . 
And I run ASOOM but the terminal shows "No frames received."  And no map is built.

What could be the cause?     Thanks for your patience.

**Comment by iandouglas96** [comment]
I can’t really support you with using something different I’m afraid.  My only thought is to make sure that the time stamps for images and odometry are exactly the same

**Comment by SSZ1** [comment]
> I can’t really support you with using something different I’m afraid. My only thought is to make sure that the time stamps for images and odometry are exactly the same

Thanks bro. I've already solved this. It was because I used the wrong topic. I'm gonna close this issue.
