### ISSUE TITLE
Orbslam3 wrapper Bug

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#2]
I used your orbslam3 wrapper and finally compiled it. I played your asoom_demo.bag and at the same time, I ran the orb_slam3_ros.launch. It showed nothing as follows:
![2e59449b934ae3a5d61b7bfb8db3c28](https://user-images.githubusercontent.com/36888758/187037658-51e22f40-148b-4eb7-90e9-0611523e3ae0.png)
![92d96b95a9f9e8ba3b7f4507c5e2629](https://user-images.githubusercontent.com/36888758/187037322-a43e6a3d-9a11-470e-a617-de5377b1ff95.png)
Then I ran rqt_graph, it showed the two ROS nodes didn't have the connection. It seemed the two nodes didn't have the subscriber. 
![4276c6be4e8d85c6ca20589c5d14df8](https://user-images.githubusercontent.com/36888758/187037397-3ec7f4a8-3f16-4ebd-8cd6-d2b4f0e703ca.png)
I wonder if your orb_slam3_ros.launch or your orbslam3 wrapper code has some errors.
![d94d1e67c9983410808ff248784aed6](https://user-images.githubusercontent.com/36888758/187037452-211219b8-1f9a-4035-bf75-2365eb9c2c30.png)

**Comment by iandouglas96** [comment]
That bag file contains compressed images, so you will need to run an image_proc node to decompress and remap to the appropriate topic.  You can see the commented out lines at the top of https://github.com/iandouglas96/asoom_oss/blob/oss/launch/asoom_iros_params.launch for an example, though you may have to modify slightly.

**Comment by SSZ1** [comment]
> 
Thanks a lot. It worked.  And how should I compress images if I wanna use my own image data?

**Comment by iandouglas96** [comment]
Good to hear!  You just need a topic of type `sensor_msgs/Image` for ASOOM and ORBSLAM3.  You can just record those directly if you want, no need to compress.  If you do want to compress images, then see http://wiki.ros.org/image_transport#Usage.  You can use this either to compress or decompress.

**Comment by SSZ1** [comment]
> Good to hear! You just need a topic of type `sensor_msgs/Image` for ASOOM and ORBSLAM3. You can just record those directly if you want, no need to compress. If you do want to compress images, then see http://wiki.ros.org/image_transport#Usage. You can use this either to compress or decompress.

Thanks a lot!!! I use my own camera. And I wanna know how to get the camera model config file. I use my Realsense D455 camera data. I observed  your ASOOM and ORB camera config file are GQ.yaml and titan_wide.yaml.  The camera config files of two project is different; the GQ.yaml is an Internal parameter file and the titan_wide is  an external parameter file. Did you use the different cameras for the ASOOM and ORB? So could you please tell how I get the Realsense D455 config file for ASOOM and ORB.  And your rosbag has the image data and the ORB pose data. BTW, do I need to run ORB using my image data first and then record the pose and the image so that I can input the image data and pose data to ASOOM ?

**Comment by iandouglas96** [comment]
Look into camera calibration extrinsics.  ORBSLAM uses its own format, but it is fairly self-explanatory.  ASOOM uses the kalibr format for camera config files, which you can read about here: https://github.com/ethz-asl/kalibr/wiki/yaml-formats.  The default parameters used in the repos are not for the same camera (and you should use titan_wide in ORBSLAM as well for best results with the provided dataset), but if you want to use your own camera you should use the same parameters for both.  The D455 ROS driver I believe publishes a `camera_info` topic which contains the information you need.  Also, if you are having a new problem with the repo, please open a new issue on the relevant repo instead of asking here.
