### ISSUE TITLE
Using Realsense D455 RGB image to run ASOOM and Questions about the camera config files.

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#3]
Hi~bro, sorry to bother you again. I have been trying using realsense D455 RGB data to run ASOOM. First I used D455 RGB data to run ORB3 and got the pose.Then I input the D455 RGB and the pose to ASOOM. But the ASOOM can't build the asoom map.
![d756b0134b30bc7fc57a968db452cc9](https://user-images.githubusercontent.com/36888758/187405633-63188da3-9014-4bd1-9e49-b246f3e2b7ab.png)

![e089166a5dcf35d0d534cece355e288](https://user-images.githubusercontent.com/36888758/187405580-ade30cde-0378-4e81-9c08-7a34d908660d.png)

![f48515161a7dd8c83bd86c0a92324f1](https://user-images.githubusercontent.com/36888758/187393649-caff1c1e-ffb6-45f6-867c-0c462f089635.jpg)

And the rqt_graph is here. It looks normal.
![afa3b37be66e3f2efc862528a033a52](https://user-images.githubusercontent.com/36888758/187393702-22757900-ef32-4eac-8933-df9edc5fdcc1.png)
But it just can't build the ASOOM map. So I'm thinking if I used the wrong camera config file resulting this. I got the D455 intrinsics by "camera_info" in ORB. But I didn't understand about the camera config file in ASOOM, So I copied the "titan_wide.ymal" and modified some parameter to D455's  intrinsics. 

You answered my last question in [https://github.com/iandouglas96/asoom_oss/issues/2](here). You said"Look into camera calibration extrinsics. ORBSLAM uses its own format, but it is fairly self-explanatory. ASOOM uses the kalibr format for camera config files, which you can read about here: https://github.com/ethz-asl/kalibr/wiki/yaml-formats. The default parameters used in the repos are not for the same camera (and you should use titan_wide in ORBSLAM as well for best results with the provided dataset), but if you want to use your own camera you should use the same parameters for both. The D455 ROS driver I believe publishes a topic which contains the information you need. Also, if you are having a new problem with the repo, please open a new issue on the relevant repo instead of asking here.camera_info" 

I have questions about the ASOOM camera config file. You said ASOOM uses the kalibr format for camera config file.But I looked into the file. It has T_cn_cnm1. 
![image](https://user-images.githubusercontent.com/36888758/187395980-f7747d10-aaad-4bf6-a6dc-6361949ff7c9.png)
![image](https://user-images.githubusercontent.com/36888758/187396451-0de95271-61f9-48af-807b-8256a4e9b4e4.png)
But D455 RGB is monocular. **So how can I get the T_cn_cnm1 of realsens D455? And does the ASOOM using multi camera? How could you get the  T_cn_cnm1 Matrix?** 

And I see kalibr here.It seems the kalibr can't solve monocular calibration. 
![image](https://user-images.githubusercontent.com/36888758/187397120-a0259318-69d5-4672-8f51-9d9321280f19.png)

I attach my two camera config files here.  Eagerly looking forward to your reply. Thanks a lot.

**Comment by SSZ1** [comment]
The camera config files I used. Thanks.
[yaml.zip](https://github.com/iandouglas96/asoom_oss/files/9451543/yaml.zip)

**Comment by iandouglas96** [comment]
ASOOM is for aerial mapping with a downward-facing camera, and you should be at least at 20m altitude, 40m would be better.  If you use indoor data like it looks like you are, then it probably won't work.  You also need GPS data, unless you set `pose_graph_fix_scale` to True, in which case you'll need to get scale some other way.  `T_cn_cnm1` isn't used for anything in ASOOM, it's just in the config file since the config was copied from kalibr's output.

**Comment by SSZ1** [comment]
> 

All right! Thanks a lot. I still have some questions.

1. Must I get the GPS data like the topic `/ublox/fix` if I want to use GPS ? But your `asoom_demo.bag` doesn't seem to have GPS topic? So how is this? 
2. And I observed the `pose_graph_fix_scale` is bool type data, If I use `pose_graph_fix_scale`, where should I set the numerical value of Scale ?  
3. So is  images, Pose and GPS/Scale  all  I need to use my data? 

Thanks for your patience.

**Comment by iandouglas96** [comment]
1. `/ublox/fix` is the GPS data.  The topic type you need is called `NavSatFix`, and they are in the demo bag.
2. If you fix the scale, then ASOOM will make the assumption that the pose data is already scaled properly. 
3. Yes.  This is what is in the demo bag.

**Comment by SSZ1** [comment]
> get scale

OK. Thanks a lot.  Any suggestions to scale the pose without GPS ? Is it OK to just get the Pose by using ORB to run aerial  images ?

I want to ask again. Is that OK if I just modify the  camera intrinsics in the config files ?

**Comment by iandouglas96** [comment]
Monocular VO, by definition, cannot provide the scale of the scene.  You need some other sensor.  It could be another camera to let you do stereo VO or it could be an IMU to do monocular VIO, both of which you can try with ORBSLAM3 (The ROS wrapper supports ORBSLAM3 in VIO mode, but you would have to modify some things to run in stereo mode).

The things you need to modify in the config files for a new camera are the instrinsics, image size, distortion model, and distortion coeffs.

**Comment by SSZ1** [comment]
> 

Thanks very much. I see very clearly now.
