### ISSUE TITLE
Question about the ublox/fix and the aerial camera.

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#4]
Hi~bro, may I ask about the specific product type of the ublox(the GPS module) and the aerial camera you using in ASOOM experiment ? Thanks a lot.

**Comment by iandouglas96** [comment]
GPS: https://www.sparkfun.com/products/16481.
The camera is a custom board called an OVC3, see https://github.com/osrf/ovc.  Any monocular camera should work fine though (realsense, pointgrey, etc.)

**Comment by SSZ1** [comment]
> GPS: https://www.sparkfun.com/products/16481.
> The camera is a custom board called an OVC2, see https://github.com/osrf/ovc. Any monocular camera should work fine though (realsense, pointgrey, etc.)

Thanks bro.
