### ISSUE TITLE
Question about getting /ublox/fix  GPS data of NavSatFix type topic. 

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#5]
Hi bro. It's me again.

I wanna know how to get the NavSatFix type topic from the GNSS receiver. My GNSS receiver is M8N and F9P from HolyBro

 So is there any open source ROS package for GNSS receiver to get the topic?  I find  a [package](https://github.com/KumarRobotics/ublox) from your group. 

Could you offer some advice?   Thanks a lot.

My GNSS receiver is as follows:
![E745F6C6121513957FCC74B893365EED](https://user-images.githubusercontent.com/36888758/192484712-d3a92ec1-83db-48cd-9ec8-0b369b6f617f.png)
![4DB52EEB121C595B6D183870D61C7D3A](https://user-images.githubusercontent.com/36888758/192484750-d323afc8-7e17-4d72-86b0-f6f36ba4b8f3.png)

**Comment by iandouglas96** [comment]
I suspect that will work with the ublox ros driver you mention.  If you are using it with a pixhawk you can also probably get the gps data through the pixhawk usb connection to a computer.  The board that I know works is https://www.sparkfun.com/products/16481.  If you have problems with the driver then please raise an issue on that repo.

**Comment by SSZ1** [comment]
> I suspect that will work with the ublox ros driver you mention. If you are using it with a pixhawk you can also probably get the gps data through the pixhawk usb connection to a computer. The board that I know works is https://www.sparkfun.com/products/16481. If you have problems with the driver then please raise an issue on that repo.

Thanks bro.  And will the type of GPS data from pixhawk be NavSatFix ? Would you mind telling me what ros driver you use to pick the NavSatFix type topic up？

**Comment by iandouglas96** [comment]
I’m not sure, but probably.

**Comment by SSZ1** [comment]
> Would you mind telling me what ros driver you use to pick the NavSatFix type topic up？

Would you mind telling me what ros driver you use to pick the NavSatFix type topic up？

**Comment by SSZ1** [comment]
> Would you mind telling me what ros driver you use to pick the NavSatFix type topic up？

Would you mind telling me what ros driver you use to pick the NavSatFix type topic up in ASOOM project？

**Comment by iandouglas96** [comment]
The driver that you referenced in combination with the module I linked to earlier

**Comment by SSZ1** [comment]
> The driver that you referenced in combination with the module I linked to earlier

Thanks very much.
