### ISSUE TITLE
Question about the speed of UAV and GNSS setting

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#6]
Hi~ bro, me again.   For GNSS， did you set the base station and the mobile station for RTK data or just use the GPS data directly?  Besides, about the flying  speed, would you mind telling me what the speed of UAV is in the experiment?

**Comment by iandouglas96** [comment]
No RTK.  The speed varies between 1 and 5 m/s in different experiments, I think we used around 2 m/s for the paper experiments.

**Comment by SSZ1** [comment]
> 

Thanks a lot.
