### ISSUE TITLE
How to test the asoom_demo.bag after catkin build in the asoom_oss-oss?

### ISSUE THREAD

**Issue by ydb1098323556** [iandouglas96/asoom_oss#7]
Hello! I'd like to ask how can I test after catkin build in the asoom_oss-oss?

**Comment by iandouglas96** [comment]
Follow the instructions in the README under "Test Data" at the bottom.  You can also run the unit tests with `catkin run_tests asoom`

**Comment by ydb1098323556** [comment]
Sorry, when I follow the instructions in the README I found following questions.


![2022-10-20 14-52-44屏幕截图](https://user-images.githubusercontent.com/106864156/196877714-607d70e6-1c89-486c-8205-cdc87a76e085.png)

What's more, I can't use "tab" to complete my command when I type in "rosparam set /u".

Is there any command I missed before test?

**Comment by iandouglas96** [comment]
Your catkin workspace is probably configured incorrectly.  See https://catkin-tools.readthedocs.io/en/latest/quick_start.html for the documentation on how it should be setup.  You also might not be properly sourcing the top level ros config at ‘/opt/ros/<distro>/setup.bash’

**Comment by ydb1098323556** [comment]
Thanks a lot! I got it. But now I met a new question.
I unzipped the correct grid_map package in "catkin_ws/src" and ran "catkin build", then I met such problem. How can I solve it?
![Screenshot from 2022-10-23 00-41-05](https://user-images.githubusercontent.com/106864156/197352077-209f7d1b-c44d-4076-b172-e383182d29d6.png)

**Comment by iandouglas96** [comment]
It looks like your OpenCV install might be incorrect

**Comment by ydb1098323556** [comment]
Hello! I have reinstalled opencv and build my workspace correctly. And I can run the command in README smoothly. Now I have result like followings:
![Screenshot from 2022-10-27 01-06-27](https://user-images.githubusercontent.com/106864156/198091238-e7ac0ff6-bf74-4447-b874-bdcfdda6795a.png)

Are my results correct?

If they are correct, next I'd want to know how to show the result in rviz.

**Comment by iandouglas96** [comment]
Open rviz then load `launch/viz.rviz`

**Comment by ydb1098323556** [comment]
Thanks a lot! With your help, I have correctly run the code.
