### ISSUE TITLE
Problems when running my own data

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#8]
Hi~bro, thanks for your time.  me again. 
I collected images of realsense with the camera below the UAV and GPS data. Then I ran the ASOOM project using my own data. But the orthographic map wasn't built completely and normally. It was incomplete, disordered, and very strange.  
So why can't it build the complete map? What could be the cause?
There seemed to be a lot of drift in the ORBSLAM process. Maybe the flight of UAV is not steady.

Here is [the experiment video](https://drive.google.com/file/d/1mmc-yTVVpJBoxkEbT5-MktOLEX5u8SR9/view?usp=sharing).  Could you offer me some advice? Thanks a lot.

**Comment by iandouglas96** [comment]
Looks to me like orbslam is struggling.  If orbslam tracking is poor then asoom will struggle.  The first thing to check is orbslam calibration.  If that fails, then you might want to spend some time adjusting the orbslam parameters

**Comment by SSZ1** [comment]
> Looks to me like orbslam is struggling. If orbslam tracking is poor then asoom will struggle. The first thing to check is orbslam calibration. If that fails, then you might want to spend some time adjusting the orbslam parameters

Oh， Thanks.
I found  it was actually the orbslam struggling. And I modified the camera config file to more accurately and reran the asoom project using my own data collected by realsense. It seemed the built map is upside-down. And the Camera orientation is converse like this:
![image](https://user-images.githubusercontent.com/36888758/196586236-161b9149-2bfb-46e9-bb29-c4c5b12ce4df.png)

so why is this? Mabey some advice?

**Comment by iandouglas96** [comment]
One thing to try is setting `pose_graph_fix_scale` to `false` and then not sending the GPS data.  The scale will be totally wrong, but  you can verify that the motion in ASOOM looks like the motion in ORBSLAM, and you can also visualize the stereo pointcloud and verify that that looks reasonable.

**Comment by SSZ1** [comment]
> 

Oh~ I see. And I found the pose_graph_fix_scale had already been set to false. And Could the pose_graph_fix be set to true when there is no GPS ?

**Comment by SSZ1** [comment]
> One thing to try is setting `pose_graph_fix_scale` to `false` and then not sending the GPS data. The scale will be totally wrong, but you can verify that the motion in ASOOM looks like the motion in ORBSLAM, and you can also visualize the stereo pointcloud and verify that that looks reasonable.

I did it as you say(just rename the GPS topic different from my GPS data in the launch file). But it can't build the map and it showed nothing in rviz. So does this mean that the  ORBSLAM did struggle?

**Comment by SSZ1** [comment]
I'm gonna offer [the collected data `chip00.bag`  and config files](https://drive.google.com/drive/folders/1ZzxNdOYgXUxx172lcMvIeXWs8__1Xryk?usp=sharing) to you. Could you help find the problem, please? In this bag, the GPS data is` /f9p/fix`. And the image data is `/camera/color/image_raw/compressed`. And `RealsenseD455modified.yaml` is the config file used in the ASOOM project. `D455.yaml` is the config file used in the Orbslam3. (Thanks a lot )× 3. 
 Here is the [Google Drive link](https://drive.google.com/drive/folders/1ZzxNdOYgXUxx172lcMvIeXWs8__1Xryk?usp=sharing).Thanks a lot.

**Comment by iandouglas96** [comment]
My mistake, I misspoke.  You want to set pose_graph_fix_scale to true to not use gps.

**Comment by SSZ1** [comment]
> My mistake, I misspoke. You want to set pose_graph_fix_scale to true to not use gps.

All right. I did it so. And the result showed the map built is still scattered. It's incomplete.
Here is the[ result video](https://drive.google.com/file/d/1_NL8lu7ePkldQ8LdCFYpX2YqQfSqYB0A/view?usp=sharing). Thanks for your kindly help.

**Comment by iandouglas96** [comment]
The orbslam map looks messed up to me, with those two overlapping planes.  I would focus first on getting orbslam to be very solid.  You can experiment with starting orbslam at different points in the bag, sometimes that can help.  The asoom map is messed up in part because the scale is extremely small.  You can either try initializing orbslam somewhere else in the dataset and hope it chooses a different scale or you can adjust the fixed scale on line 15 of pose_graph.cpp to something other than 1 to approximate what it actually is.

**Comment by SSZ1** [comment]
> The orbslam map looks messed up to me, with those two overlapping planes. I would focus first on getting orbslam to be very solid. You can experiment with starting orbslam at different points in the bag, sometimes that can help. The asoom map is messed up in part because the scale is extremely small. You can either try initializing orbslam somewhere else in the dataset and hope it chooses a different scale or you can adjust the fixed scale on line 15 of pose_graph.cpp to something other than 1 to approximate what it actually is.

Oh~thanks very much.
