### ISSUE TITLE
Does Frequency of Topic influence the performance of ASOOM? 

### ISSUE THREAD

**Issue by SSZ1** [iandouglas96/asoom_oss#9]
I realized that the frequency of '/orbslam3_ros_node/pose' is 20hz and the frequency of '/ublox/fix' is 10hz. So does the frequency of topics influence the performance of ASOOM? If it influences the performance, how does frequency influence it ?

**Comment by iandouglas96** [comment]
No, aside from higher frequencies possibly increasing the compute load slightly.  No need for the gps and odom frequencies to be the same.

**Comment by SSZ1** [comment]
> 

Thanks bro.
